spring.application.name=Sklep internetowy
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./sklep_db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

